"""empty message

Revision ID: d4dbfc2bec19
Revises: 
Create Date: 2020-12-09 01:40:53.124392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4dbfc2bec19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('courses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('courses', 'students_of_course',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('courses_owner_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'students', ['owner_id'], ['id'])
    op.alter_column('requests', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('requests', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('students', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('students', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('students', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('teachers', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('teachers', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('teachers', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('teachers', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('teachers', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('teachers', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('students', 'password',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('students', 'lastname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('students', 'firstname',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('requests', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requests', 'course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_owner_id_fkey', 'courses', 'teachers', ['owner_id'], ['id'])
    op.alter_column('courses', 'students_of_course',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('courses', 'name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
